[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[schemes.ayu_dark.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[schemes.ayu_dark.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[schemes.ayu_dark.primary]
background = "#0A0E14"
foreground = "#B3B1AD"

[schemes.monokai_pro.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.monokai_pro.normal]
black = "#403E41"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[schemes.monokai_pro.primary]
background = "#2D2A2E"
foreground = "#FCFCFA"

[window.padding]
x = 5
y = 2
